name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Python dependencies
      run: |
        cd whatsapp-mcp-server
        pip install -r requirements.txt

    - name: Install Node.js dependencies
      run: |
        cd whatsapp-bridge
        npm install

    - name: Run Python tests
      run: |
        cd whatsapp-mcp-server
        python -m pytest --version || echo "No tests found"

    - name: Check code formatting
      run: |
        python -m pip install black
        black --check whatsapp-mcp-server/ || echo "Code formatting issues found"

    - name: Lint JavaScript
      run: |
        cd whatsapp-bridge
        npx eslint whatsapp-bridge-server.js || echo "Linting issues found"

  docker:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build MCP Server Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./whatsapp-mcp-server
        push: false
        tags: whatsapp-mcp-server:latest

    - name: Build Bridge Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./whatsapp-bridge
        push: false
        tags: whatsapp-bridge:latest

    - name: Test Docker Compose
      run: |
        docker-compose -f docker-compose.whatsapp.yaml config
